### ISSUE TITLE
Incorrect processing of IEMOCAP data

### ISSUE THREAD

**Issue by nikosanto13** [lixiangucas01/GLAM#2]
Hello, 
First of all, thank you for sharing your implementation. I'd like to point out that in the line 310 of process.py, you have (erroneously, as far as I am concerned) commented the key '03' which corresponds to the happy emotion. I reckon that the common practice is to merge excitement and happiness, not completely replacing the latter with the former.

**Comment by Thinkre** [comment]
We have mentioned in our paper that we label excited as happy category for consistent of previous works
